### ISSUE TITLE
Invalid offset when reading record from an older version

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#19379]
**Describe the bug**

```
java.lang.RuntimeException: Failed to replay batch at 'LoggedEvent [position=405952032, key=-1, timestamp=1718125492239, sourceEventPosition=405952031] RecordMetadata{recordType=EVENT, valueType=CHECKPOINT, intent=CREATED, rejectionType=INVALID_ARGUMENT, authorization=UNKNOWN}'
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$4(ReplayStateMachine.java:170) ~[zeebe-stream-platform-8.3.12.jar:8.3.12]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.3.12.jar:8.3.12]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:96) ~[zeebe-scheduler-8.3.12.jar:8.3.12]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.3.12.jar:8.3.12]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.3.12.jar:8.3.12]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.3.12.jar:8.3.12]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.3.12.jar:8.3.12]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.3.12.jar:8.3.12]
Caused by: java.lang.IllegalArgumentException: invalid offset: -65442
	at org.agrona.concurrent.UnsafeBuffer.boundsCheckWrap(UnsafeBuffer.java:662) ~[agrona-1.19.2.jar:1.19.2]
	at org.agrona.concurrent.UnsafeBuffer.wrap(UnsafeBuffer.java:286) ~[agrona-1.19.2.jar:1.19.2]
	at io.camunda.zeebe.msgpack.spec.MsgPackReader.wrap(MsgPackReader.java:49) ~[zeebe-msgpack-core-8.3.12.jar:8.3.12]
	at io.camunda.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:40) ~[zeebe-msgpack-value-8.3.12.jar:8.3.12]
	at io.camunda.zeebe.logstreams.impl.log.LoggedEventImpl.readValue(LoggedEventImpl.java:106) ~[zeebe-logstreams-8.3.12.jar:8.3.12]
	at io.camunda.zeebe.stream.impl.records.RecordValues.readRecordValue(RecordValues.java:34) ~[zeebe-stream-platform-8.3.12.jar:8.3.12]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.readRecordValue(ReplayStateMachine.java:312) ~[zeebe-stream-platform-8.3.12.jar:8.3.12]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.replayEvent(ReplayStateMachine.java:229) ~[zeebe-stream-platform-8.3.12.jar:8.3.12]
```

Following events happened before this error.

1. Cluster is at version 8.2.15
2. Cluster takes a backup
3. Cluster restores from this backup
4. After sometime, it was updated to 8.2.28. This is when we first see this error.

Root cause analysis:

To allow larger records, we had changes the metadataLength field in `LogEntryDescriptor` from short to int. https://github.com/camunda/camunda/pull/15991 The assumption was that since we use little endian, [changing the read from getShort() to getInt()](https://github.com/camunda/camunda/pull/15991/commits/160ae30b9cf28879df92d298ce1d700b86552c5c) will return the same value for the old version which used a short. This is mostly correct. But in this case, there were garbage values in the unused higher bytes. As a result `metadataLength` read as int returned invalid value. 

Why was garbage value here? The journal was truncated immediately after restore (this is expected.). During truncation we only mark the record as invalid by writing zeros to the header. We do not zero the whole record. The new record was written to the same location as the previous record. Since we did not zeroed it, there might be garbage values in the previously unused bytes. The version which writes this record was also 8.2.15 which writes the metadata as short. So it do not overwrite these unused bytes. 

After the broker is upgraded to a version that used integer for `metadataLength`, it reads these garbage bytes resulting in invalid length.

**To Reproduce**

Restore from backup in a version from before the above bug fix. After that, upgrade the cluster to a version with the above bug fix, before it has a chance to take a snapshot and compact. 

Related to https://camunda.slack.com/archives/C077X0MKYQ5

**Comment by npepinpe** [comment]
@deepthidevaki - I believe this is fixed, right?

**Comment by deepthidevaki** [comment]
No. This is not fixed. We were able to recover the cluster from the backup. So we didn't push for the patch.

**Comment by npepinpe** [comment]
Oh, then let me assign someone to work on this as it's a critical issue :)
