### ISSUE TITLE
Unable to Assign Zeebe User Task in C8Run 8.7.0-alpha1 & 8.6.5 

### ISSUE THREAD

**Issue by slolatte** [camunda/camunda#24808]
**Describe the issue:**

https://jira.camunda.com/browse/SUPPORT-25953

When using C8Run with `8.7.0-alpha1` and `8.6.5` , I am unable to assign a Zeebe User Task. 

**Actual behavior:**

When attempting to assign a Zeebe User Task, the task does not get assigned as expected.

**Expected behavior:**

I would expect to be able to assign a Zeebe User Task without any issues.

**How to reproduce:**

1. Set up C8Run with version `8.7.0-alpha1` or `8.6.5` .
2. Deploy a diagram with a Zeebe User Task
3. Attempt to assign a Zeebe User Task in the UI.
4. Observe that the task is not assigned and an error appears in the UI (see screenshot)
![Screenshot 2024-11-15 at 17 33 31](https://github.com/user-attachments/assets/af971585-07f8-4419-9a33-b9bafc47bbbb)

*Note:* The issue occurs across all operating systems.

**Logs:**

I have attached logs and a screenshot of the UI behavior for reference.
[camunda.log](https://github.com/user-attachments/files/17799747/camunda.log)

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- **Platform:** Mac, Windows, Linux
- **Architecture:** x86, ARM
- **Version:** 8.7.0-alpha1 and 8.6.5

**Comment by abda1014** [comment]
Do u still have this bug ?

**Comment by slolatte** [comment]
@abda1014 Yes it is still occurring

**Comment by marinator86** [comment]
@abda1014 It is also occuring for us

**Comment by abda1014** [comment]
Is this fixed ? i currently use the saas version and  everything works there.

**Comment by houssain-barouni** [comment]
@slolatte This has been solved in 8.7.0-alpha3 release

**Comment by slolatte** [comment]
@houssain-barouni This issue is still occurring for me when using the main branch of the camunda/camunda repository. Should the fix be there?

**Comment by houssain-barouni** [comment]
> @houssain-barouni This issue is still occurring for me when using the main branch of the camunda/camunda repository. Should the fix be there?

Hi @slolatte , how are you testing ?

**Comment by slolatte** [comment]
> > @houssain-barouni This issue is still occurring for me when using the main branch of the camunda/camunda repository. Should the fix be there?
> 
> Hi @slolatte , how are you testing ?

@houssain-barouni 

1. I pulled the latest changes from the repository
2. I navigate to the c8Run folder
3. I run `go build` in the terminal
4. I run `./c8run package` in the terminal
5. I run `./c8run start` in the terminal

Once C8Run is active, I deploy the attached diagram. Then I navigate to Tasklist, click the 'Assign to Me' button for this diagram and observe the error above. 
[Zeebe_User_Task.bpmn.zip](https://github.com/user-attachments/files/18333779/Zeebe_User_Task.bpmn.zip)

**Comment by slolatte** [comment]
@houssain-barouni I would say that since Zeebe User Tasks won't be able to be assigned without this being set, that we should always have this be set with C8Run. @jessesimpson36 WDYT?

**Comment by houssain-barouni** [comment]
> @houssain-barouni I would say that since Zeebe User Tasks won't be able to be assigned without this being set, that we should always have this be set with C8Run. @jessesimpson36 WDYT?

@slolatte in C8 8.7.0-alpha3, Tasklist does not do any REST calls to Zeebe when run in C8 single app.
Can you show me which c8run release you have used? do you still have recent logs?

**Comment by houssain-barouni** [comment]
> @houssain-barouni For this, I didn't use any release, I used the latest code in the `main `branch and the `8.6 `branch from the` camunda/camunda` repo. From my understanding, the `8.7.0-alpha3` fixes should be in the `main` branch, or am I wrong?

the c8run in main still points to 8.7.0-alpha2: https://github.com/camunda/camunda/blob/927deb937cc097963365f786c5970c3fa9376bfe/c8run/main.go#L196

I guess this will bumped to alpha3 once the release is created, @jessesimpson36 can you please confirm that?

>Also, will this fix be back-ported to the 8.6 branch or how can this issue be fixed there? 

I am afraid that the fix will not be backported to 8.6, as it will be very complex to do that. Anyway, we already knew the single app will have some limitations in 8.6 like the authentication and this issue.

**Comment by slolatte** [comment]
@houssain-barouni Thanks for the update, we will remove the Zeebe User Task automated test from the test suite for 8.6 then. Once C8Run is bumped for `8.7.0-alpha3` I will retest this and provide an update!

**Comment by gbetances089** [comment]
This is fix on C8Run 8.7 alpha3

https://github.com/user-attachments/assets/77fc90b2-83bb-4467-bb63-1551095780c0

**Comment by ingorichtsmeier** [comment]
Reopening, as 8.6.6 is still affected.

I found some suspicious outputs in the logs:

```
2024-11-15 15:42:05.338 [] [main] [] INFO 
      io.camunda.tasklist.zeebe.ZeebeConnector - Zeebe Client - Using REST Configuration: http://localhost:8089
2024-11-15 15:42:05.338 [] [main] [] INFO 
      io.camunda.tasklist.zeebe.ZeebeConnector - Zeebe Client - Using Gateway Configuration: localhost:26500
```

and 

```
2024-11-15 16:20:04.326 [] [http-nio-0.0.0.0-8080-exec-7] [] WARN 
      io.camunda.tasklist.webapp.api.rest.v1.controllers.TaskController - io.camunda.zeebe.client.api.command.ClientException: org.apache.hc.client5.http.HttpHostConnectException: Connect to http://localhost:8089 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
io.camunda.tasklist.exceptions.TasklistRuntimeException: io.camunda.zeebe.client.api.command.ClientException: org.apache.hc.client5.http.HttpHostConnectException: Connect to http://localhost:8089 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
	at io.camunda.tasklist.webapp.service.TaskService.assignTask(TaskService.java:164) ~[tasklist-webapp-8.7.0-alpha1.jar:8.7.0-alpha1]
	at io.camunda.tasklist.webapp.api.rest.v1.controllers.TaskController.assignTask(TaskController.java:297) ~[tasklist-webapp-8.7.0-alpha1.jar:8.7.0-alpha1]
```

Where is the configuration of the Zeebe client for Tasklist to use port 8089 instead of port 8080?

**Comment by gbetances089** [comment]
Hi @ingorichtsmeier the issue was only fix on the 8.7 version, it was not backported to 8.6 (original [ticket](https://github.com/camunda/camunda/issues/21818) used by tasklist to fix this. @houssain-barouni can confirm this.

**Comment by houssain-barouni** [comment]
> Hi [@ingorichtsmeier](https://github.com/ingorichtsmeier) the issue was only fix on the 8.7 version, it was not backported to 8.6 (original [ticket](https://github.com/camunda/camunda/issues/21818) used by tasklist to fix this) [@houssain-barouni](https://github.com/houssain-barouni) can confirm this.

Yes, I confirm that the fix is part of 8.7.0-alpha3, it can tested with this version
Backporting it to 8.6 will be quite complex, because it depends on streamlining implementation.

> Where is the configuration of the Zeebe client for Tasklist to use port 8089 instead of port 8080?

The configuration is `CAMUNDA_TASKLIST_ZEEBE_RESTADDRESS` that should be set with `http://localhost:8080`, after setting the configuration, you will face another issue that was solved in alpha3. Note that `CAMUNDA_TASKLIST_ZEEBE_RESTADDRESS` is not required anymore in alpha3 as Tasklist does broker requests instead of REST calls to Zeebe engine

**Comment by hisImminence** [comment]
Thanks, I tried to reproduce it with 8.6.6 and 8.6.7 and could assign tasks to for me (maybe because I chose `authentication: None`?)

<img width="303" alt="Image" src="https://github.com/user-attachments/assets/21880c47-bd9b-4a24-8912-668ffc748153" />

> Yes, I confirm that the fix is part of 8.7.0-alpha3, it can tested with this version
> Backporting it to 8.6 will be quite complex, because it depends on streamlining implementation.

@houssain-barouni, does this mean we dont plan to fix this in 8.6? With my understanding this would then mean that this bug will also be present in the next alphas and the 8.7 release then as we changed the scope now  - excluding all streamlining related changes for 8.7. Is my assumption correct?

**Comment by houssain-barouni** [comment]
Hi @hisImminence 
> Thanks, I tried to reproduce it with 8.6.6 and 8.6.7 and could assign tasks to for me (maybe because I chose authentication: None?)
Maybe you are testing with "legacy" job workers and not Zeebe user tasks 

<img width="557" alt="Image" src="https://github.com/user-attachments/assets/085a6e9c-68d9-4123-a863-5ad80a6f0b32" />

> @houssain-barouni, does this mean we dont plan to fix this in 8.6? With my understanding this would then mean that this bug will also be present in the next alphas and the 8.7 release then as we changed the scope now - excluding all streamlining related changes for 8.7. Is my assumption correct?

Correct, the issue will remain in 8.7. Otherwise, we need to assess the **importance** and **feasibility** of a backport to 8.7 cc @marcosgvieira

**Comment by ingorichtsmeier** [comment]
I've double-checked and this is my failing process, using a Camunda user task:

[error-example Kopie.bpmn.txt](https://github.com/user-attachments/files/18505704/error-example.Kopie.bpmn.txt)

Using a Job worker user task in another process works for me as well.

Maybe this difference is handled in another ticket, but it's still a bug. Camunda user tasks should be supported with 8.6: https://docs.camunda.io/docs/components/modeler/bpmn/user-tasks/#define-a-user-task

**Comment by houssain-barouni** [comment]
> Camunda user tasks should be supported with 8.6

That's correct, but the single application and C8run, is it expected to be 100% working in 8.6? because there are other limitations related to authentication topics, which also causes this issue with the Zeebe user tasks in Tasklist.

**Comment by ingorichtsmeier** [comment]
Our customers do expect that Camunda 8 Run is working with all process automation features.

They are developing a process locally with Camunda 8 run and deploy it after a local successful test to a central test environment having Identity as well.

**Comment by marcosgvieira** [comment]
@aleksander-dytko can you please provide product perspective here - would this be acceptable to be a known issue for 8.7?

**Comment by hisImminence** [comment]
@aleksander-dytko, fyi we got another customer raising an issue with this topic [SUPPORT-24876](https://jira.camunda.com/browse/SUPPORT-24876).

cc. reported by @RajSubburaj1820 [here](https://camunda.slack.com/archives/C074T8BTTM2/p1737657554799139?thread_ts=1737649709.910449&cid=C074T8BTTM2)

**Comment by marcosgvieira** [comment]
We had discussions internally (@marcosgvieira @aleksander-dytko @houssain-barouni @romansmirnov ) on what would be the best way to fix this issue and I would like to bring transparency here:

- We are going to fix that for 8.6.x versions, meaning that C8Run should work with Zeebe User Tasks on 8.6.x version
- We probably won't make this fix for our next release 8.6.7 but potentially for 8.6.8 because of capacity constraints
- The workaround that we do have for customers on 8.6.6 and below would be to spin up Zeebe in a different instance than Tasklist - using that configuration this problem should go away (I understand this is not ideal and not good for C8Run, but anyway documenting it here)

**Comment by houssain-barouni** [comment]
As agreed, the fix has been [backported](https://github.com/camunda/camunda/pull/27641) to 8.7 and 8.6 and will be part of `8.7.0-alpha5` and `8.6.9`

**Comment by houssain-barouni** [comment]
Hi @slolatte , @gbetances089 ,
The fix is pushed to stable/8.7 and stable/8.6. Can you please test it with the latest 8.7 snapshot ?

**Comment by gbetances089** [comment]
@houssain-barouni so we tried now with the RC for both 8.6 and 8.7 and we found it worked fine for 8.6.9 but failed on 8.7.0alpha4

Video 
https://github.com/user-attachments/assets/0198b4e9-10b9-4d2c-b898-117054771db3

You can download the RC [here](https://github.com/camunda/camunda/actions/runs/13293948374)

**Comment by houssain-barouni** [comment]
> @houssain-barouni so we tried now with the RC for both 8.6 and 8.7 and we found it worked fine for 8.6.9 but failed on 8.7.0alpha4,  I know you comment the fix for 8.7 would be for alpha5, is this still the timeline?
> 
> Video 
> https://github.com/user-attachments/assets/0198b4e9-10b9-4d2c-b898-117054771db3
> 
> You can download the 8.7.0alpha4 RC [here](https://github.com/camunda/camunda/actions/runs/13293948374)

This is correct, it is planned to be part of alpha5. Maybe you can try to test using 8.7.0-SNAPSHOT artifact

**Comment by marcosgvieira** [comment]
@houssain-barouni , should we close this one?

**Comment by houssain-barouni** [comment]
> [@houssain-barouni](https://github.com/houssain-barouni) , should we close this one?

I think a QA validation for 8.7 is remaining. @gbetances089 did you manage to test with 8.7.0-SNAPSHOT ?

**Comment by kevinCamunda** [comment]
@houssain-barouni is this fixed with 8.8 alpha2? I just encountered the issue. I was assigning fine yesterday, and today it's failing.

**Comment by kevinCamunda** [comment]
@houssain-barouni removed the task listener, reployed, and it worked fine. I'll troubleshoot some more and see if it's a "me" issue, or something else.
