### ISSUE TITLE
./start.sh command - failed with error 'open .env: no such file or directory'

### ISSUE THREAD

**Issue by gbetances089** [camunda/camunda#27735]
**Describe the issue:**

On Mac/Windows execute the start command and the distro fails to start.

**Actual behavior:**

You get the following messages:

Mac:

`$ ./start.sh
open .env: no such file or directory
Java version is 21.0.5
Starting Elasticsearch ...
(Hint: you can find the log output in the 'elasticsearch.log' file in the 'log' folder of your distribution.)
fork/exec /Users/gustavobetances/Downloads/c8run/elasticsearch-/bin/elasticsearch: no such file or directory%`

Windows:

`C:\Users\GustavoBetances\Downloads\camunda8-run-8.6.8-windows-x86_64> .\c8run.exe start
open .env: The system cannot find the file specified.
Failed to check if filepath is a symlink`

**Expected behavior:**

The distro comes up as is usually do.

**How to reproduce:**

1. Download the released version from [here](https://github.com/camunda/camunda/releases/tag/8.6.8)
2. Unzip
3. Execute the start command.

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Architecture: 
- Version:

**Comment by aabouzaid** [comment]
This should be fixed here https://github.com/camunda/camunda/pull/27736
And the RC is released here:
https://github.com/camunda/camunda/releases/tag/c8run-8.6-rc

**Comment by gbetances089** [comment]
Tested on the lastest RC and looks good!

**Comment by Kleptomancy** [comment]
Tested with the mentioned RC-Release, still not working on the following setup:
Win 11 Home - 10.0.26100, with JDK 23. Already ran PowerShell as admin and also tested it with JDK 21 ... 


This is my error-message (as mentioned in the issue):
![Image](https://github.com/user-attachments/assets/0223d4cd-c6f9-4a88-9640-f01e045b384d)
