### ISSUE TITLE
Tasklist is not handling rejection/delays of listeners

### ISSUE THREAD

**Issue by esraagamal6** [camunda/camunda#27846]
### Describe the Bug  
When task assignment or completion fails or is delayed, the system always displays a "Service unreachable" message instead of a more accurate notification, such as "Task cannot be completed" or "Task assignment delayed."  

### To Reproduce  

1. In Modeler, add a listener to a User Task with the type `"assigning"`.  
2. Run the process.  
3. Open the User Task and, from the network tab in DevTools, simulate a slow connection.  
4. Click "Assign."  
For more scenarios refer to this [test case](https://camunda.testrail.com/index.php?/cases/view/577448)

  

https://github.com/user-attachments/assets/8833b020-ed21-4386-9901-75ad40b7aafc

### Actual Behavior  
The displayed message is: **"Task could not be assigned. Service unreachable."**  

### Expected Behavior  
A more accurate notification should be displayed, such as: **"Task assignment delayed."** as in the [design](https://docs.google.com/document/d/1BxvvkdDJurzblKcnjbP00sUE3FCv5rDM81IOG4OG_cM/edit?tab=t.0#heading=h.ak839ldyiwxs)
### Environment

- OS: [e.g. MacOS]
- Browser: [e.g. chrome, safari]
- Tasklist Version: 8.8.0-alpha1

### Additional context

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### After solving the issue - Answer and document in the comments the questions below

- [ ] What was the root cause for this bug?
- [ ] Is there anything we should do for the error to not happen anymore?

**Comment by tsedekey** [comment]
@esraagamal6 I noticed that this bug is only apparent when the Tasklist is run with Zebee 8.7 or lower. I tried testing it locally with Zebee 8.8-alpha4 and I couldn't reproduce the issue. I believe this bug is also resolved by changes made by this [PR](https://github.com/camunda/camunda/pull/26877). Please can it be retested to confirm.

**Comment by esraagamal6** [comment]
Retested with @tsedekey  on `8.8.0-alpah2-rc1` and was still reproducible via the attached app

[zeebe-test (11).zip](https://github.com/user-attachments/files/19011106/zeebe-test.11.zip)

**Comment by marcosgvieira** [comment]
@tsedekey can you please have a look here?

**Comment by tsedekey** [comment]
> [@tsedekey](https://github.com/tsedekey) can you please have a look here?

@marcosgvieira I have opened a [PR](https://github.com/camunda/camunda/pull/31808) that should address this bug.

**Comment by tsedekey** [comment]
Hi @esraagamal6, just a quick note — this issue should be addressed by the recent merge of this [PR](https://github.com/camunda/camunda/pull/31808). Could you please retest when you get a chance and let me know if any issues remain?
