### ISSUE TITLE
Failed to replay batch at 'LoggedEvent [..] RecordMetadata{recordType=EVENT, valueType=PROCESS_INSTANCE_BATCH, intent=UNKNOWN, authorization=UNKNOWN}'

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#30810]
### Component

Zeebe-

### Severity

Critical-

### Likelihood

High_

### Description

> [!NOTE]
> This bug leads to unavailability but not data loss.

```
Failed to replay batch at 'LoggedEvent [..] RecordMetadata{recordType=EVENT, valueType=PROCESS_INSTANCE_BATCH, intent=UNKNOWN, authorization=UNKNOWN}'
```

This error can occur when a broker is updated to a version that does not know about the new `ACTIVATED` or `TERMINATED` intents:
https://github.com/camunda/camunda/blob/2bf8331b15a0cb2840a6fccfbe9942d29c315e63/zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/intent/ProcessInstanceBatchIntent.java#L21-L22

When the error occurs, the partition is marked DEAD on that broker. If this occurs on a quorum, then this leads to unavailability.

### Steps to reproduce

- Create a cluster on `8.6.13`
- Deploy a process with a multi-intance element
- Create an instance of this process, activating the multi-instance
- Now update the cluster to `8.7.0`
- Notice that the updated brokers will mark the partitions as DEAD (or inactive)

### Current behavior

> [!NOTE]
> This bug leads to unavailability but not data loss.

The events are unknown to the updated broker, and can thus not be applied to the state.
As replay cannot be continued on the partition, the partition needs to shutdown.
This can result in unavailability when an quorum encounters the same problem.

### Expected behavior

WIP

### Environment

SaaS & SM

### Version

- Component Version: `8.7.0`

### Rootcause

`ProcessInstanceBatchIntent` contains intents on `8.6.13` that don't exist on `8.7.0`.

**8.6.13**
https://github.com/camunda/camunda/blob/2bf8331b15a0cb2840a6fccfbe9942d29c315e63/zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/intent/ProcessInstanceBatchIntent.java#L19-L22

**8.7.0**
https://github.com/camunda/camunda/blob/f508f35d5b470996eca828405fb70ebcd24977a8/zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/intent/ProcessInstanceBatchIntent.java#L19-L20

**stable/8.7**
https://github.com/camunda/camunda/blob/f3090e11c51d388b10e1a973ff0dd70496392911/zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/intent/ProcessInstanceBatchIntent.java#L19-L22

**They are no-op appliers**
https://github.com/camunda/camunda/blob/69b38f64870c237a6a85171822c93fc653bfc853/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/EventAppliers.java#L95-L96

### Solution ideas

The fix was already merged to `stable/8.7`, but not in time for the code freeze of `8.7.0`:
- https://github.com/camunda/camunda/pull/29562

We can simply release `8.7.1` from `stable/8.7`.

We should consider a way to test against incorrectly ported/released changes.

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

[#inc-dead-partitions-in-enterprise-dev-cluster](https://camunda.slack.com/archives/C08M68KCPE2)

**Comment by korthout** [comment]
Closing this as completed, as we've released [`8.7.1`](https://github.com/camunda/camunda/releases/tag/8.7.1) with the fix.

**Comment by rodrigo-lourenco-lopes** [comment]
We see this error still in several clusters:

```
StreamProcessor-1 failed, marking it as dead: HealthReport[componentName=StreamProcessor-1, status=DEAD, issue=HealthIssue[message=null, throwable=java.lang.RuntimeException: Failed to replay batch at 'LoggedEvent [position=17400224, key=2251799822383926, timestamp=1753142719403, sourceEventPosition=17400175] RecordMetadata{recordType=EVENT, valueType=IDENTITY_SETUP, intent=INITIALIZED, authorization=AuthInfo{format=UNKNOWN, authData=, claims={}}}', cause=null, since=2025-07-22T00:07:17.222Z], children={}]
```

Which later leads to a `Partition-1 failed, marking it as dead` loop.

These are being observed in zeebe-SNAPSHOT.

Clusters:
https://console.cloud.google.com/errors/detail/CJen7e_I-5vgQw;service=zeebe;time=P7D;locations=global?inv=1&invt=Ab3g1Q&project=camunda-saas-int
https://console.cloud.google.com/errors/detail/CI3brc_K2qCeLA;service=zeebe;time=P7D;locations=global?inv=1&invt=Ab3g1g&project=camunda-saas-int

**Comment by rodrigo-lourenco-lopes** [comment]
Also here: https://console.cloud.google.com/errors/detail/CI3brc_K2qCeLA;service=zeebe;time=P7D;locations=global?inv=1&invt=Ab3g2w&project=camunda-saas-dev

**Comment by rodrigo-lourenco-lopes** [comment]
And here: https://console.cloud.google.com/errors/detail/CI3brc_K2qCeLA;service=zeebe;time=P7D;locations=global?inv=1&invt=Ab3gyQ&project=camunda-saas-int-chaos

**Comment by korthout** [comment]
@rodrigo-lourenco-lopes This is a critical bug. Please provide more context:
- on what version did you see this?
- direct link to the logs
- download the logs and store them in Drive and link those

**Comment by korthout** [comment]
The error is as follows:

>Exporter-1 failed, marking it as dead: HealthReport[componentName=Exporter-1, status=DEAD, issue=HealthIssue[message=null, throwable=io.camunda.zeebe.util.exception.UnrecoverableException: java.lang.RuntimeException: Could not deserialize object [MappingRuleRecord]. Deserialization stuck at offset 195 of length 195, cause=null, since=2025-07-22T16:52:17.225Z], children={}]

That's a different error than this issue covered. @rodrigo-lourenco-lopes please open a new issue and investigate to the point where we know the severity so it can be triaged.

**Comment by korthout** [comment]
Closing again as completed in `8.7.1`
