### ISSUE TITLE
Operate displays the number of process and element instances when a user has only the permission to read process definitions

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#38198]
### 

### 

### 

### 

### Description

* When a user has only the permission to read process definitions, they can still see in Operate
  * how many instances of that definition exist (`/api/incidents/byProcess`)
  * The number of element instances per element (`/v2/process-definitions/<id>/statistics/element-instances`)

### Steps to reproduce

1. Deploy a process model
2. Have a user that has only READ_PROCESS_DEFINITION * on the PROCESS_DEFINITION resource
3. Open Operate

### Current behavior

* Operate displays the number of process instances of that process on the dashboard
* Operate displays the number of element instances of that process in the processes view

### Expected behavior

* Both numbers are not displayed, as the user has no access to the process instances

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SaaS & SM

### Version

- Component Version: [e.g. 2.0.0]

### Breakdown

- [x] Fix authorization checks for `/api/incidents/byProcess`: https://github.com/camunda/camunda/pull/38689
- [x] Fix authorization checks for `/v2/process-definitions/<id>/statistics/element-instances`: https://github.com/camunda/camunda/pull/48304

### Dev -> QA handover

- Resources:
- Versions to validate: 8.8 and 8.9
- Release version (in which version this feature will be released): 8.9.0, 8.8.19

Note: This issue only fixes it for ES/OS. There is a separate issue for RDBMS: https://github.com/camunda/camunda/issues/48780

**Comment by kristinkomschow** [comment]
I fixed this for the internal API but won't have time for V2 in the next ~two weeks, so I'll get the first fix merged for now and added a breakdown to the description.

**Comment by bmudric** [comment]
@kristinkomschow  hi, can you please tell me if you are still working on it / will be working on completing this task?

**Comment by kristinkomschow** [comment]
@bmudric I'm not currently working on this. I fixed this for the mentioned V1 API because I had some capacity at the time but have since been working on other topics. I could probably continue with this some time mid/end of next week (dependent on medic workload), but if the Identity team wants to pick this up meanwhile feel free to do so.

**Comment by npepinpe** [comment]
I assume you did not have time :)

I will re-assign this 👍

**Comment by ana-vinogradova-camunda** [comment]
I've investigated this issue:

1. The first point (showing how many instances of the definition exist (`/api/incidents/byProcess`)) was fixed. However, the number is still shown (as zero) and I can see that the new search was not used. Example of a new search can be found [here](https://github.com/camunda/camunda/blob/f295fe008b9d603916fac36e0bd1facf5497c43f/service/src/main/java/io/camunda/service/ProcessDefinitionServices.java#L54).
2.  The second point: I can reproduce the issue, currently, `/v2/process-definitions/<id>/statistics/element-instances` returns counts for elements instances even though the correct permission is applied in the [search](https://github.com/camunda/camunda/blob/f295fe008b9d603916fac36e0bd1facf5497c43f/service/src/main/java/io/camunda/service/ProcessDefinitionServices.java#L64):
```
public List<ProcessFlowNodeStatisticsEntity> elementStatistics(
      final ProcessDefinitionStatisticsFilter filter) {
    return executeSearchRequest(
        () ->
            processDefinitionSearchClient
                .withSecurityContext(
                    securityContextProvider.provideSecurityContext(
                        authentication, PROCESS_DEFINITION_READ_AUTHORIZATION))
                .processDefinitionFlowNodeStatistics(filter));
  }
```

@eppdot I wonder if you could take a look as it looks to me the issue goes deeper than Identity?
@bmudric could you please review my findings?

Thank you

**Comment by npepinpe** [comment]
For point 1, this seems to be related to the internal API which is just not using the new authorization model, and it should be migrated.

FYI for @eppdot , our assumption here is that you'd need to also check for `PROCESS_INSTANCE_READ_AUTHORIZATION`, meaning "Is this user allowed to see process instances?". Right now, what we check in the Operate controller is just "Is this user allowed to see the process definition?". But since you check the count of element instances, which is tied to PIs, then it might make sense to also check for that permission.

In that sense, the library is fine, but the code is just not looking at the right permissions.

Anyway, I'm removing it from our board, as it's an Operate issue.

**Comment by eppdot** [comment]
@ThorbenLindhauer I assume the expected behavior is confirmed with PM? (I could also see reasons, that these counts are okay to have even though you only have the definition permissions)

@npepinpe I agree it's for core features, but it also sounds like straight forward to fix? (add one more check in the controller/service layer?) - I don't think we will work on this very soon, but could be a good first issue 😏

**Comment by ThorbenLindhauer** [comment]
I don't recall that to be honest.

**Comment by eppdot** [comment]
> I don't recall that to be honest.

np, @aleksander-dytko / @volodymyr-melnykc wdyt? 😄

**Comment by npepinpe** [comment]
> @npepinpe I agree it's for core features, but it also sounds like straight forward to fix? (add one more check in the controller/service layer?) - I don't think we will work on this very soon, but could be a good first issue 😏

Yeah, we didn't do it ourselves mostly because it's a product decision to some extent (e.g. requiring a new permission for endpoint X)

As for the first point (the controller which isn't using the new authorization stuff), that's just more refactoring, and I have no clue if that's a quick fix.

So there's 2 things that need to be changed, and IDK if the first one is a good first issue (as in, I truly can't say 🤷)

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | BUG |
| **Severity** | 🔥 HIGH |
| **Likelihood** | ⚠️ Mid |
| **Confidence** | 0.95 |

---

### 📝 Rationale

The issue describes a clear bug: users with only process definition read permission can see process and element instance counts in Operate, which is not expected. This is an incorrect behavior in a released product, matching the definition of a BUG. Severity is HIGH because it exposes potentially sensitive operational data to unauthorized users, which is a significant security and privacy concern, though it does not cause data loss or system unavailability. Likelihood is MID, as it affects users with a specific permission configuration, but is not universal. The issue is well described, with expected vs actual behavior and reproduction steps, and falls within Core Features team boundaries.

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.

**Comment by marcosgvieira** [comment]
🔄 **Status updated automatically (Core Features)**

**From:** Backlog  
**To:** Ready  

**Reason:** The issue already has an assignee.

**Comment by marcosgvieira** [comment]
🔄 **Iteration updated automatically (Core Features)**

**From:** Mar M1 (8.9)  
**To:** Mar M2 (8.9)  

**Reason:** The issue is In Progress, so it should be part of the current iteration.

**Comment by tanjinyi** [comment]
> > I don't recall that to be honest.
> 
> np, [@aleksander-dytko](https://github.com/aleksander-dytko) / [@volodymyr-melnykc](https://github.com/volodymyr-melnykc) wdyt? 😄

Hey @aleksander-dytko / @volodymyr-melnykc, in case this one missed your attention. I'm currently looking at replacing the the existing READ_PROCESS_DEFINITION permission requirement with the READ_PROCESS_INSTANCE permission for the process definition element instance statistics endpoint. Would this be fine?

**Comment by tanjinyi** [comment]
Just an FYI by the way, the V1 endpoint for `/api/incidents/byProcess` has been removed as of [#46431](https://github.com/camunda/camunda/pull/46431). The changes to fix the authorisation will only be needed in 8.8.

**Comment by YuliaKorsun** [comment]
@ThorbenLindhauer could you please clarify if wildcard resource ID (PROCESS_DEFINITION:*:READ_PROCESS_INSTANCE) is mandatory, or should process-scoped permissions (PROCESS_DEFINITION:new:READ_PROCESS_INSTANCE) work as well?

 I've noticed the next behavior in my testing today on 8.9.0-snapshot. 

**Setup:**

- User has full BATCH and PROCESS DEFINITION authorization scoped to a specific `process ID=new`
- NOT using wildcard (*) for resource ID - permission is scoped **to the specific process**

<img width="1581" height="660" alt="Image" src="https://github.com/user-attachments/assets/87d046ad-ea8a-421a-9376-4fcef228e413" />


**Current behavior:**

- User can view the process diagram in Operate, but element instance statistics (active token badges) are NOT displayed on the diagram
- Whereas Admin user CAN see the element instance statistics (because it has wildcard Recourse ID permission)

**As per original bug description**: When user has access to the process instances, they should see element instance statistics for that process. 

But my User with **full** permissions **for a specific process** **doesn't** see element instance statistics for that process:

<img width="1724" height="1006" alt="Image" src="https://github.com/user-attachments/assets/4fad4761-5149-4239-bf26-ec4afa3757ad" />

Admin user with wildcard * process permission: 
<img width="2143" height="1166" alt="Image" src="https://github.com/user-attachments/assets/dda700e9-1cba-4e8b-8ce6-1810db22db07" />

**Comment by ThorbenLindhauer** [comment]
@YuliaKorsun yeah, I'd expect that case to work, too. Maybe you can sync with @tanjinyi if his PR fixes this case.

**Comment by kristinkomschow** [comment]
> @YuliaKorsun yeah, I'd expect that case to work, too. Maybe you can sync with @tanjinyi if his PR fixes this case.

Putting this here since I checked this during review:

This isn't fixed in the current state of the PR.

Root cause:
The query is done on the `operate-list-view` index. It applies must-clauses for `joinRelation == activity` (to only return element instances and not process instances) and `processDefinitionKey == {key}` (as specified in the search query) in the [filter transformer](https://github.com/camunda/camunda/blob/main/search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/ProcessDefinitionStatisticsFilterTransformer.java#L69-L73). The authorization then adds a must-clause for `bpmnProcessId == {authorizedProcesses}`, but since this value is not set for element instances (only process instances) this results in no hits.

**Comment by volodymyr-melnykc** [comment]
**[SEE THE CORRECTED RESPONSE [HERE](https://github.com/camunda/camunda/issues/38198#issuecomment-4090500155)]**


@tanjinyi @aleksander-dytko My feedback and expectation for the following two scenarios:
- What permission level is required to see how many instances a process definition has
- What permission level is required to see the number of element instances per element in a process definition

### Instance count per process definition

To see how many instances a process definition has, the user needs one of the following:

- `READ_PROCESS_DEFINITION` permission on the `PROCESS_DEFINITION` resource -> this grants access to the definition overall, and would make sense to show the instance count as a part of it. My understanding is that this data is also retrieved via the process definition-related API endpoint [Get process instance statistics](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/get-process-definition-instance-statistics/).
- `READ_PROCESS_INSTANCE` permission on the `PROCESS_DEFINITION` resource with wildcard assignment (read access to all process instances).

### Element instance count per element

The same two permissions should apply here. My understanding is that this data is retrieved from a process-definition-level API endpoint [Get process definition statistics](https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/get-process-definition-statistics/), so the access rules should be consistent with the above. A user with either `READ_PROCESS_DEFINITION` or wildcard `READ_PROCESS_INSTANCE` on the `PROCESS_DEFINITION` resource should be able to see element-level instance counts.

cc @ThorbenLindhauer

**Comment by aleksander-dytko** [comment]
I'd push back on allowing `READ_PROCESS_DEFINITION` alone to surface instance counts. Instance counts and element instance counts are fundamentally instance-level data - the fact that they're returned from a process-definition-scoped API endpoint is an implementation detail, not a reflection of what permission should govern them. A user granted only definition access (e.g. to review the BPMN model) should not implicitly receive visibility into how many instances are running or where they are in the flow. That would violate least-privilege and could leak operational/business-sensitive information.

My expectation for both endpoints:
- `READ_PROCESS_DEFINITION` only -> counts not displayed
- `READ_PROCESS_INSTANCE` on the `PROCESS_DEFINITION` resource -> counts displayed

On the wildcard-only restriction: I agree with @ThorbenLindhauer comment that process-scoped `READ_PROCESS_INSTANCE` permissions (e.g. scoped to a specific process definition key) should also grant visibility into counts for that process. Requiring wildcard-only creates an inconsistency where a user can interact with a specific process's instances via API but still can't see statistics in Operate.

**Comment by volodymyr-melnykc** [comment]
After speaking with Thorben yesterday, I agree that `READ_PROCESS_INSTANCE` should be sufficient to see instance counts for a process definition. Plus for the reasons @aleksander-dytko described above.

> process-scoped READ_PROCESS_INSTANCE permissions (e.g. scoped to a specific process definition key) should also grant visibility into counts for that process. Requiring wildcard-only creates an inconsistency where a user can interact with a specific process's instances via API but still can't see statistics in Operate.

It also makes sense to me! @tanjinyi

**Comment by kristinkomschow** [comment]
We'd already talked about the feedback and had implemented it that way since it made the most sense, but good to have the full approval. I'm going ahead and merge the PR since @tanjinyi is on FTO tomorrow.

Note: The fix currently only works for ES/OS. There is a[ separate issue for RDBMS](https://github.com/camunda/camunda/issues/48780)

**Comment by YuliaKorsun** [comment]
Tested on SM envs:  version: 8.9-SNAPSHOT and 8.8.18

| READ_PROCESS_DEFINITION | READ_PROCESS_INSTANCE      | Observed result |
|---|---|---|
| * | - | Instance/element counts and active tokens not shown |
| process_definition_id | - | Instance/element counts and and active tokens not shown |
| - | * | Instance/element counts shown. Process view/diagram not accessible (missing READ_PROCESS_DEFINITION) |
| - | process_definition_id | Instance/element counts shown. Process view/diagram not accessible (missing READ_PROCESS_DEFINITION) |
| * | * | Instance/element counts shown |
| process_definition_id | process_definition_id | Instance/element counts shown |
