### ISSUE TITLE
GET audit log returns 404

### ISSUE THREAD

**Issue by YuliaKorsun** [camunda/camunda#42736]
### 

### 

### 

### 

### Description

I run request according to the spec: https://docs.camunda.io/docs/next/apis-tools/orchestration-cluster-api-rest/specifications/get-audit-log/
but 404 is returned 

### Steps to reproduce

I run the project locally with the latest snapshot: 

```
Run curl --location 'http://localhost:8080/v2/audit-logs/oTYEzfWjxjZao4smjnK1GrHwUg5CdTR4' \
--header 'Accept: application/json' \
--header 'Authorization: Basic ZGVtbzpkZW1v' \
```

### Current behavior

<img width="1199" height="758" alt="Image" src="https://github.com/user-attachments/assets/2b755108-8607-43a8-88e6-b8f763b9bbd0" />

```
{
    "type": "about:blank",
    "title": "NOT_FOUND",
    "status": 404,
    "detail": "Audit log with id 'oTYEzfWjxjZao4smjnK1GrHwUg5CdTR4' not found",
    "instance": "/v2/audit-logs/oTYEzfWjxjZao4smjnK1GrHwUg5CdTR4"
}
```

### Expected behavior

Results should be returned

### Workaround

1. do this
2. do that
3. now this happens and circumvents the bug

### Environment

SM

### Version

- Component Version: Version 8.9.0-SNAPSHOT

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

**Comment by koevskinikola** [comment]
@YuliaKorsun this one is fixed now correct? Can we close it?

**Comment by YuliaKorsun** [comment]
@koevskinikola are you sure? I don't see any linked PRs and the error is still reproducible for me. 

<img width="1195" height="717" alt="Image" src="https://github.com/user-attachments/assets/39deea82-abf4-4243-a71d-4d67c5d30f97" />

**Comment by koevskinikola** [comment]
@YuliaKorsun, I found the issue. It will be fixed with https://github.com/camunda/camunda/pull/42791

**Comment by koevskinikola** [comment]
Resolved with https://github.com/camunda/camunda/pull/42791
